// 自动生成,请勿手改。改法:改 data/raw-lazyvim.json 后重跑 scripts/build-dataset.mjs
//
// 来源:290 条,从本机 LazyVim 会话的 nvim_get_keymap 实测抽取。
// 全部 status="mapped"(键确实存在,含义取自插件 desc,未经逐条亲验)。
//
// 跳过:33 条 Insert/Select + 9 条 auto-pairs
//     + 10 条 desc 是 help 引用 + 23 条无描述
//     + 0 条非用户接口

import type { Binding } from "./matcher";

export const GROUPS: Record<string, string> = {
  "window": "窗口",
  "buffer": "缓冲区",
  "single": "单键",
  "file": "文件查找",
  "upper": "大写键",
  "multi": "多键序列",
  "session": "会话",
  "ctrl-b": "Ctrl-b 系列",
  "git": "Git",
  "special": "特殊键",
  "code": "代码 / LSP",
  "search": "搜索替换",
  "ui": "界面",
  "leader-other": "其他 leader 键",
};

export const LEVEL_NAMES: Record<number, string> = {
  1: "第 1 关 · 立刻要会",
  2: "第 2 关",
  3: "第 3 关",
  4: "第 4 关",
  5: "第 5 关",
  6: "第 6 关",
  7: "第 7 关",
  8: "第 8 关",
  10: "第 10 关",
};

export const RAW: Omit<Binding, "keys">[] = [
 {
  "id": "n:<C-Down>",
  "display": "<C-Down>",
  "label": "Decrease Window Height",
  "desc": "Decrease Window Height",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<C-H>",
  "display": "<C-H>",
  "label": "Go to Left Window",
  "desc": "Go to Left Window",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<C-J>",
  "display": "<C-J>",
  "label": "Go to Lower Window",
  "desc": "Go to Lower Window",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<C-K>",
  "display": "<C-K>",
  "label": "Go to Upper Window",
  "desc": "Go to Upper Window",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<C-L>",
  "display": "<C-L>",
  "label": "Go to Right Window",
  "desc": "Go to Right Window",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<C-Left>",
  "display": "<C-Left>",
  "label": "Decrease Window Width",
  "desc": "Decrease Window Width",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<C-Right>",
  "display": "<C-Right>",
  "label": "Increase Window Width",
  "desc": "Increase Window Width",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<C-Up>",
  "display": "<C-Up>",
  "label": "Increase Window Height",
  "desc": "Increase Window Height",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<Space>wd",
  "display": "<Space>wd",
  "label": "Delete Window",
  "desc": "Delete Window",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<Space>wm",
  "display": "<Space>wm",
  "label": "Toggle Zoom Mode",
  "desc": "Toggle Zoom Mode",
  "mode": "n",
  "group": "window",
  "groupLabel": "窗口",
  "level": 1,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bb",
  "display": "<Space>bb",
  "label": "Switch to Other Buffer",
  "desc": "Switch to Other Buffer",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bd",
  "display": "<Space>bd",
  "label": "Delete Buffer",
  "desc": "Delete Buffer",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bD",
  "display": "<Space>bD",
  "label": "Delete Buffer and Window",
  "desc": "Delete Buffer and Window",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bi",
  "display": "<Space>bi",
  "label": "Delete Invisible Buffers",
  "desc": "Delete Invisible Buffers",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bj",
  "display": "<Space>bj",
  "label": "Pick Buffer",
  "desc": "Pick Buffer",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bl",
  "display": "<Space>bl",
  "label": "Delete Buffers to the Left",
  "desc": "Delete Buffers to the Left",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bo",
  "display": "<Space>bo",
  "label": "Delete Other Buffers",
  "desc": "Delete Other Buffers",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bp",
  "display": "<Space>bp",
  "label": "Toggle Pin",
  "desc": "Toggle Pin",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>bP",
  "display": "<Space>bP",
  "label": "Delete Non-Pinned Buffers",
  "desc": "Delete Non-Pinned Buffers",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>br",
  "display": "<Space>br",
  "label": "Delete Buffers to the Right",
  "desc": "Delete Buffers to the Right",
  "mode": "n",
  "group": "buffer",
  "groupLabel": "缓冲区",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "v:a",
  "display": "a",
  "label": "Around textobject",
  "desc": "Around textobject",
  "mode": "v",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "x:a",
  "display": "a",
  "label": "Around textobject",
  "desc": "Around textobject",
  "mode": "x",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "o:a",
  "display": "a",
  "label": "Around textobject",
  "desc": "Around textobject",
  "mode": "o",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "v:i",
  "display": "i",
  "label": "Inside textobject",
  "desc": "Inside textobject",
  "mode": "v",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "x:i",
  "display": "i",
  "label": "Inside textobject",
  "desc": "Inside textobject",
  "mode": "x",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "o:i",
  "display": "i",
  "label": "Inside textobject",
  "desc": "Inside textobject",
  "mode": "o",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:j",
  "display": "j",
  "label": "Down",
  "desc": "Down",
  "mode": "n",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "v:j",
  "display": "j",
  "label": "Down",
  "desc": "Down",
  "mode": "v",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "x:j",
  "display": "j",
  "label": "Down",
  "desc": "Down",
  "mode": "x",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:k",
  "display": "k",
  "label": "Up",
  "desc": "Up",
  "mode": "n",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "v:k",
  "display": "k",
  "label": "Up",
  "desc": "Up",
  "mode": "v",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "x:k",
  "display": "k",
  "label": "Up",
  "desc": "Up",
  "mode": "x",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:n",
  "display": "n",
  "label": "Next Search Result",
  "desc": "Next Search Result",
  "mode": "n",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "v:n",
  "display": "n",
  "label": "Next Search Result",
  "desc": "Next Search Result",
  "mode": "v",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "x:n",
  "display": "n",
  "label": "Next Search Result",
  "desc": "Next Search Result",
  "mode": "x",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "o:n",
  "display": "n",
  "label": "Next Search Result",
  "desc": "Next Search Result",
  "mode": "o",
  "group": "single",
  "groupLabel": "单键",
  "level": 2,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fb",
  "display": "<Space>fb",
  "label": "Buffers",
  "desc": "Buffers",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fB",
  "display": "<Space>fB",
  "label": "Buffers (all)",
  "desc": "Buffers (all)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fc",
  "display": "<Space>fc",
  "label": "Find Config File",
  "desc": "Find Config File",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fe",
  "display": "<Space>fe",
  "label": "Explorer Snacks (root dir)",
  "desc": "Explorer Snacks (root dir)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fE",
  "display": "<Space>fE",
  "label": "Explorer Snacks (cwd)",
  "desc": "Explorer Snacks (cwd)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ff",
  "display": "<Space>ff",
  "label": "Find Files (Root Dir)",
  "desc": "Find Files (Root Dir)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fF",
  "display": "<Space>fF",
  "label": "Find Files (cwd)",
  "desc": "Find Files (cwd)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fg",
  "display": "<Space>fg",
  "label": "Find Files (git-files)",
  "desc": "Find Files (git-files)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fn",
  "display": "<Space>fn",
  "label": "New File",
  "desc": "New File",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fp",
  "display": "<Space>fp",
  "label": "Projects",
  "desc": "Projects",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fr",
  "display": "<Space>fr",
  "label": "Recent",
  "desc": "Recent",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fR",
  "display": "<Space>fR",
  "label": "Recent (cwd)",
  "desc": "Recent (cwd)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ft",
  "display": "<Space>ft",
  "label": "Terminal (Root Dir)",
  "desc": "Terminal (Root Dir)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:<Space>fT",
  "display": "<Space>fT",
  "label": "Terminal (cwd)",
  "desc": "Terminal (cwd)",
  "mode": "n",
  "group": "file",
  "groupLabel": "文件查找",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:H",
  "display": "H",
  "label": "Prev Buffer",
  "desc": "Prev Buffer",
  "mode": "n",
  "group": "upper",
  "groupLabel": "大写键",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:L",
  "display": "L",
  "label": "Next Buffer",
  "desc": "Next Buffer",
  "mode": "n",
  "group": "upper",
  "groupLabel": "大写键",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:N",
  "display": "N",
  "label": "Prev Search Result",
  "desc": "Prev Search Result",
  "mode": "n",
  "group": "upper",
  "groupLabel": "大写键",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "v:N",
  "display": "N",
  "label": "Prev Search Result",
  "desc": "Prev Search Result",
  "mode": "v",
  "group": "upper",
  "groupLabel": "大写键",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "x:N",
  "display": "N",
  "label": "Prev Search Result",
  "desc": "Prev Search Result",
  "mode": "x",
  "group": "upper",
  "groupLabel": "大写键",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "o:N",
  "display": "N",
  "label": "Prev Search Result",
  "desc": "Prev Search Result",
  "mode": "o",
  "group": "upper",
  "groupLabel": "大写键",
  "level": 3,
  "status": "mapped"
 },
 {
  "id": "n:[ ",
  "display": "[ ",
  "label": "Add empty line above cursor",
  "desc": "Add empty line above cursor",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[<C-L>",
  "display": "[<C-L>",
  "label": ":lpfile",
  "desc": ":lpfile",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[<C-Q>",
  "display": "[<C-Q>",
  "label": ":cpfile",
  "desc": ":cpfile",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[<C-T>",
  "display": "[<C-T>",
  "label": " :ptprevious",
  "desc": " :ptprevious",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[a",
  "display": "[a",
  "label": ":previous",
  "desc": ":previous",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[A",
  "display": "[A",
  "label": ":rewind",
  "desc": ":rewind",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[b",
  "display": "[b",
  "label": "Prev Buffer",
  "desc": "Prev Buffer",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[B",
  "display": "[B",
  "label": "Move buffer prev",
  "desc": "Move buffer prev",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[d",
  "display": "[d",
  "label": "Prev Diagnostic",
  "desc": "Prev Diagnostic",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[D",
  "display": "[D",
  "label": "Jump to the first diagnostic in the current buffer",
  "desc": "Jump to the first diagnostic in the current buffer",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[e",
  "display": "[e",
  "label": "Prev Error",
  "desc": "Prev Error",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[l",
  "display": "[l",
  "label": ":lprevious",
  "desc": ":lprevious",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[L",
  "display": "[L",
  "label": ":lrewind",
  "desc": ":lrewind",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[q",
  "display": "[q",
  "label": "Previous Trouble/Quickfix Item",
  "desc": "Previous Trouble/Quickfix Item",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[Q",
  "display": "[Q",
  "label": ":crewind",
  "desc": ":crewind",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[t",
  "display": "[t",
  "label": "Previous Todo Comment",
  "desc": "Previous Todo Comment",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[T",
  "display": "[T",
  "label": ":trewind",
  "desc": ":trewind",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:[w",
  "display": "[w",
  "label": "Prev Warning",
  "desc": "Prev Warning",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:] ",
  "display": "] ",
  "label": "Add empty line below cursor",
  "desc": "Add empty line below cursor",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]<C-L>",
  "display": "]<C-L>",
  "label": ":lnfile",
  "desc": ":lnfile",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]<C-Q>",
  "display": "]<C-Q>",
  "label": ":cnfile",
  "desc": ":cnfile",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]<C-T>",
  "display": "]<C-T>",
  "label": ":ptnext",
  "desc": ":ptnext",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]a",
  "display": "]a",
  "label": ":next",
  "desc": ":next",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]A",
  "display": "]A",
  "label": ":last",
  "desc": ":last",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]b",
  "display": "]b",
  "label": "Next Buffer",
  "desc": "Next Buffer",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]B",
  "display": "]B",
  "label": "Move buffer next",
  "desc": "Move buffer next",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]d",
  "display": "]d",
  "label": "Next Diagnostic",
  "desc": "Next Diagnostic",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]D",
  "display": "]D",
  "label": "Jump to the last diagnostic in the current buffer",
  "desc": "Jump to the last diagnostic in the current buffer",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]e",
  "display": "]e",
  "label": "Next Error",
  "desc": "Next Error",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]l",
  "display": "]l",
  "label": ":lnext",
  "desc": ":lnext",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]L",
  "display": "]L",
  "label": ":llast",
  "desc": ":llast",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]q",
  "display": "]q",
  "label": "Next Trouble/Quickfix Item",
  "desc": "Next Trouble/Quickfix Item",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]Q",
  "display": "]Q",
  "label": ":clast",
  "desc": ":clast",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]t",
  "display": "]t",
  "label": "Next Todo Comment",
  "desc": "Next Todo Comment",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]T",
  "display": "]T",
  "label": ":tlast",
  "desc": ":tlast",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:]w",
  "display": "]w",
  "label": "Next Warning",
  "desc": "Next Warning",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:<Space>qd",
  "display": "<Space>qd",
  "label": "Don't Save Current Session",
  "desc": "Don't Save Current Session",
  "mode": "n",
  "group": "session",
  "groupLabel": "会话",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ql",
  "display": "<Space>ql",
  "label": "Restore Last Session",
  "desc": "Restore Last Session",
  "mode": "n",
  "group": "session",
  "groupLabel": "会话",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:<Space>qq",
  "display": "<Space>qq",
  "label": "Quit All",
  "desc": "Quit All",
  "mode": "n",
  "group": "session",
  "groupLabel": "会话",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:<Space>qs",
  "display": "<Space>qs",
  "label": "Restore Session",
  "desc": "Restore Session",
  "mode": "n",
  "group": "session",
  "groupLabel": "会话",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:<Space>qS",
  "display": "<Space>qS",
  "label": "Select Session",
  "desc": "Select Session",
  "mode": "n",
  "group": "session",
  "groupLabel": "会话",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:al",
  "display": "al",
  "label": "Around last textobject",
  "desc": "Around last textobject",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:al",
  "display": "al",
  "label": "Around last textobject",
  "desc": "Around last textobject",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "o:al",
  "display": "al",
  "label": "Around last textobject",
  "desc": "Around last textobject",
  "mode": "o",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:an",
  "display": "an",
  "label": "Around next textobject",
  "desc": "Around next textobject",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:an",
  "display": "an",
  "label": "Around next textobject",
  "desc": "Around next textobject",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "o:an",
  "display": "an",
  "label": "Around next textobject",
  "desc": "Around next textobject",
  "mode": "o",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:g[",
  "display": "g[",
  "label": "Move to left \"around\"",
  "desc": "Move to left \"around\"",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:g[",
  "display": "g[",
  "label": "Move to left \"around\"",
  "desc": "Move to left \"around\"",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:g[",
  "display": "g[",
  "label": "Move to left \"around\"",
  "desc": "Move to left \"around\"",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "o:g[",
  "display": "g[",
  "label": "Move to left \"around\"",
  "desc": "Move to left \"around\"",
  "mode": "o",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:g]",
  "display": "g]",
  "label": "Move to right \"around\"",
  "desc": "Move to right \"around\"",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:g]",
  "display": "g]",
  "label": "Move to right \"around\"",
  "desc": "Move to right \"around\"",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:g]",
  "display": "g]",
  "label": "Move to right \"around\"",
  "desc": "Move to right \"around\"",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "o:g]",
  "display": "g]",
  "label": "Move to right \"around\"",
  "desc": "Move to right \"around\"",
  "mode": "o",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:gc",
  "display": "gc",
  "label": "Toggle comment",
  "desc": "Toggle comment",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:gc",
  "display": "gc",
  "label": "Toggle comment",
  "desc": "Toggle comment",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:gc",
  "display": "gc",
  "label": "Toggle comment",
  "desc": "Toggle comment",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "o:gc",
  "display": "gc",
  "label": "Comment textobject",
  "desc": "Comment textobject",
  "mode": "o",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:gcc",
  "display": "gcc",
  "label": "Toggle comment line",
  "desc": "Toggle comment line",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:gco",
  "display": "gco",
  "label": "Add Comment Below",
  "desc": "Add Comment Below",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:gcO",
  "display": "gcO",
  "label": "Add Comment Above",
  "desc": "Add Comment Above",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:gO",
  "display": "gO",
  "label": "vim.lsp.buf.document_symbol()",
  "desc": "vim.lsp.buf.document_symbol()",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:gra",
  "display": "gra",
  "label": "vim.lsp.buf.code_action()",
  "desc": "vim.lsp.buf.code_action()",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:gra",
  "display": "gra",
  "label": "vim.lsp.buf.code_action()",
  "desc": "vim.lsp.buf.code_action()",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:gra",
  "display": "gra",
  "label": "vim.lsp.buf.code_action()",
  "desc": "vim.lsp.buf.code_action()",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:gri",
  "display": "gri",
  "label": "vim.lsp.buf.implementation()",
  "desc": "vim.lsp.buf.implementation()",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:grn",
  "display": "grn",
  "label": "vim.lsp.buf.rename()",
  "desc": "vim.lsp.buf.rename()",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:grr",
  "display": "grr",
  "label": "vim.lsp.buf.references()",
  "desc": "vim.lsp.buf.references()",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:grt",
  "display": "grt",
  "label": "vim.lsp.buf.type_definition()",
  "desc": "vim.lsp.buf.type_definition()",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:gx",
  "display": "gx",
  "label": "Opens filepath or URI under cursor with the system handler (file explorer, web browser, …)",
  "desc": "Opens filepath or URI under cursor with the system handler (file explorer, web browser, …)",
  "mode": "n",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:gx",
  "display": "gx",
  "label": "Opens filepath or URI under cursor with the system handler (file explorer, web browser, …)",
  "desc": "Opens filepath or URI under cursor with the system handler (file explorer, web browser, …)",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:gx",
  "display": "gx",
  "label": "Opens filepath or URI under cursor with the system handler (file explorer, web browser, …)",
  "desc": "Opens filepath or URI under cursor with the system handler (file explorer, web browser, …)",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:il",
  "display": "il",
  "label": "Inside last textobject",
  "desc": "Inside last textobject",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:il",
  "display": "il",
  "label": "Inside last textobject",
  "desc": "Inside last textobject",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "o:il",
  "display": "il",
  "label": "Inside last textobject",
  "desc": "Inside last textobject",
  "mode": "o",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "v:in",
  "display": "in",
  "label": "Inside next textobject",
  "desc": "Inside next textobject",
  "mode": "v",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "x:in",
  "display": "in",
  "label": "Inside next textobject",
  "desc": "Inside next textobject",
  "mode": "x",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "o:in",
  "display": "in",
  "label": "Inside next textobject",
  "desc": "Inside next textobject",
  "mode": "o",
  "group": "multi",
  "groupLabel": "多键序列",
  "level": 4,
  "status": "mapped"
 },
 {
  "id": "n:<C-B>",
  "display": "<C-B>",
  "label": "Scroll Backward",
  "desc": "Scroll Backward",
  "mode": "n",
  "group": "ctrl-b",
  "groupLabel": "Ctrl-b 系列",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "v:<C-B>",
  "display": "<C-B>",
  "label": "Scroll Backward",
  "desc": "Scroll Backward",
  "mode": "v",
  "group": "ctrl-b",
  "groupLabel": "Ctrl-b 系列",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gb",
  "display": "<Space>gb",
  "label": "Git Blame Line",
  "desc": "Git Blame Line",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gB",
  "display": "<Space>gB",
  "label": "Git Browse (open)",
  "desc": "Git Browse (open)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "v:<Space>gB",
  "display": "<Space>gB",
  "label": "Git Browse (open)",
  "desc": "Git Browse (open)",
  "mode": "v",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "x:<Space>gB",
  "display": "<Space>gB",
  "label": "Git Browse (open)",
  "desc": "Git Browse (open)",
  "mode": "x",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gd",
  "display": "<Space>gd",
  "label": "Git Diff (hunks)",
  "desc": "Git Diff (hunks)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gD",
  "display": "<Space>gD",
  "label": "Git Diff (origin)",
  "desc": "Git Diff (origin)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gf",
  "display": "<Space>gf",
  "label": "Git Current File History",
  "desc": "Git Current File History",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gi",
  "display": "<Space>gi",
  "label": "GitHub Issues (open)",
  "desc": "GitHub Issues (open)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gI",
  "display": "<Space>gI",
  "label": "GitHub Issues (all)",
  "desc": "GitHub Issues (all)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gl",
  "display": "<Space>gl",
  "label": "Git Log",
  "desc": "Git Log",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gL",
  "display": "<Space>gL",
  "label": "Git Log (cwd)",
  "desc": "Git Log (cwd)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gp",
  "display": "<Space>gp",
  "label": "GitHub Pull Requests (open)",
  "desc": "GitHub Pull Requests (open)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gP",
  "display": "<Space>gP",
  "label": "GitHub Pull Requests (all)",
  "desc": "GitHub Pull Requests (all)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gs",
  "display": "<Space>gs",
  "label": "Git Status",
  "desc": "Git Status",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gS",
  "display": "<Space>gS",
  "label": "Git Stash",
  "desc": "Git Stash",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "n:<Space>gY",
  "display": "<Space>gY",
  "label": "Git Browse (copy)",
  "desc": "Git Browse (copy)",
  "mode": "n",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "v:<Space>gY",
  "display": "<Space>gY",
  "label": "Git Browse (copy)",
  "desc": "Git Browse (copy)",
  "mode": "v",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "x:<Space>gY",
  "display": "<Space>gY",
  "label": "Git Browse (copy)",
  "desc": "Git Browse (copy)",
  "mode": "x",
  "group": "git",
  "groupLabel": "Git",
  "level": 5,
  "status": "mapped"
 },
 {
  "id": "c:<BS>",
  "display": "<BS>",
  "label": "MiniPairs <BS>",
  "desc": "MiniPairs <BS>",
  "mode": "c",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<C-_>",
  "display": "<C-_>",
  "label": "which_key_ignore",
  "desc": "which_key_ignore",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<C-/>",
  "display": "<C-/>",
  "label": "Terminal (Root Dir)",
  "desc": "Terminal (Root Dir)",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<C-F>",
  "display": "<C-F>",
  "label": "Scroll Forward",
  "desc": "Scroll Forward",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<C-F>",
  "display": "<C-F>",
  "label": "Scroll Forward",
  "desc": "Scroll Forward",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<C-S>",
  "display": "<C-S>",
  "label": "Save File",
  "desc": "Save File",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<C-S>",
  "display": "<C-S>",
  "label": "Save File",
  "desc": "Save File",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "x:<C-S>",
  "display": "<C-S>",
  "label": "Save File",
  "desc": "Save File",
  "mode": "x",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<C-W> ",
  "display": "<C-W> ",
  "label": "Window Hydra Mode (which-key)",
  "desc": "Window Hydra Mode (which-key)",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<C-W><C-D>",
  "display": "<C-W><C-D>",
  "label": "Show diagnostics under the cursor",
  "desc": "Show diagnostics under the cursor",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<C-W>d",
  "display": "<C-W>d",
  "label": "Show diagnostics under the cursor",
  "desc": "Show diagnostics under the cursor",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Down>",
  "display": "<Down>",
  "label": "Down",
  "desc": "Down",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<Down>",
  "display": "<Down>",
  "label": "Down",
  "desc": "Down",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "x:<Down>",
  "display": "<Down>",
  "label": "Down",
  "desc": "Down",
  "mode": "x",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Esc>",
  "display": "<Esc>",
  "label": "Escape and Clear hlsearch",
  "desc": "Escape and Clear hlsearch",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<Esc>",
  "display": "<Esc>",
  "label": "Escape and Clear hlsearch",
  "desc": "Escape and Clear hlsearch",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<M-j>",
  "display": "<M-j>",
  "label": "Move Down",
  "desc": "Move Down",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<M-j>",
  "display": "<M-j>",
  "label": "Move Down",
  "desc": "Move Down",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "x:<M-j>",
  "display": "<M-j>",
  "label": "Move Down",
  "desc": "Move Down",
  "mode": "x",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<M-k>",
  "display": "<M-k>",
  "label": "Move Up",
  "desc": "Move Up",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<M-k>",
  "display": "<M-k>",
  "label": "Move Up",
  "desc": "Move Up",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "x:<M-k>",
  "display": "<M-k>",
  "label": "Move Up",
  "desc": "Move Up",
  "mode": "x",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "c:<S-CR>",
  "display": "<S-CR>",
  "label": "Redirect Cmdline",
  "desc": "Redirect Cmdline",
  "mode": "c",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<S-Tab>",
  "display": "<S-Tab>",
  "label": "vim.snippet.jump if active, otherwise <S-Tab>",
  "desc": "vim.snippet.jump if active, otherwise <S-Tab>",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Space>cd",
  "display": "<Space>cd",
  "label": "Line Diagnostics",
  "desc": "Line Diagnostics",
  "mode": "n",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Space>cf",
  "display": "<Space>cf",
  "label": "Format",
  "desc": "Format",
  "mode": "n",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<Space>cf",
  "display": "<Space>cf",
  "label": "Format",
  "desc": "Format",
  "mode": "v",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "x:<Space>cf",
  "display": "<Space>cf",
  "label": "Format",
  "desc": "Format",
  "mode": "x",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Space>cF",
  "display": "<Space>cF",
  "label": "Format Injected Langs",
  "desc": "Format Injected Langs",
  "mode": "n",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<Space>cF",
  "display": "<Space>cF",
  "label": "Format Injected Langs",
  "desc": "Format Injected Langs",
  "mode": "v",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "x:<Space>cF",
  "display": "<Space>cF",
  "label": "Format Injected Langs",
  "desc": "Format Injected Langs",
  "mode": "x",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Space>cm",
  "display": "<Space>cm",
  "label": "Mason",
  "desc": "Mason",
  "mode": "n",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Space>cs",
  "display": "<Space>cs",
  "label": "Symbols (Trouble)",
  "desc": "Symbols (Trouble)",
  "mode": "n",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Space>cS",
  "display": "<Space>cS",
  "label": "LSP references/definitions/... (Trouble)",
  "desc": "LSP references/definitions/... (Trouble)",
  "mode": "n",
  "group": "code",
  "groupLabel": "代码 / LSP",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<Tab>",
  "display": "<Tab>",
  "label": "vim.snippet.jump if active, otherwise <Tab>",
  "desc": "vim.snippet.jump if active, otherwise <Tab>",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Up>",
  "display": "<Up>",
  "label": "Up",
  "desc": "Up",
  "mode": "n",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "v:<Up>",
  "display": "<Up>",
  "label": "Up",
  "desc": "Up",
  "mode": "v",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "x:<Up>",
  "display": "<Up>",
  "label": "Up",
  "desc": "Up",
  "mode": "x",
  "group": "special",
  "groupLabel": "特殊键",
  "level": 6,
  "status": "mapped"
 },
 {
  "id": "n:<Space>s\"",
  "display": "<Space>s\"",
  "label": "Registers",
  "desc": "Registers",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>s/",
  "display": "<Space>s/",
  "label": "Search History",
  "desc": "Search History",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sa",
  "display": "<Space>sa",
  "label": "Autocmds",
  "desc": "Autocmds",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sb",
  "display": "<Space>sb",
  "label": "Buffer Lines",
  "desc": "Buffer Lines",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sB",
  "display": "<Space>sB",
  "label": "Grep Open Buffers",
  "desc": "Grep Open Buffers",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sc",
  "display": "<Space>sc",
  "label": "Command History",
  "desc": "Command History",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sC",
  "display": "<Space>sC",
  "label": "Commands",
  "desc": "Commands",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sd",
  "display": "<Space>sd",
  "label": "Diagnostics",
  "desc": "Diagnostics",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sD",
  "display": "<Space>sD",
  "label": "Buffer Diagnostics",
  "desc": "Buffer Diagnostics",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sg",
  "display": "<Space>sg",
  "label": "Grep (Root Dir)",
  "desc": "Grep (Root Dir)",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sG",
  "display": "<Space>sG",
  "label": "Grep (cwd)",
  "desc": "Grep (cwd)",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sh",
  "display": "<Space>sh",
  "label": "Help Pages",
  "desc": "Help Pages",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sH",
  "display": "<Space>sH",
  "label": "Highlights",
  "desc": "Highlights",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>si",
  "display": "<Space>si",
  "label": "Icons",
  "desc": "Icons",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sj",
  "display": "<Space>sj",
  "label": "Jumps",
  "desc": "Jumps",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sk",
  "display": "<Space>sk",
  "label": "Keymaps",
  "desc": "Keymaps",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sl",
  "display": "<Space>sl",
  "label": "Location List",
  "desc": "Location List",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sm",
  "display": "<Space>sm",
  "label": "Marks",
  "desc": "Marks",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sM",
  "display": "<Space>sM",
  "label": "Man Pages",
  "desc": "Man Pages",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sn",
  "display": "<Space>sn",
  "label": "+noice",
  "desc": "+noice",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sna",
  "display": "<Space>sna",
  "label": "Noice All",
  "desc": "Noice All",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>snd",
  "display": "<Space>snd",
  "label": "Dismiss All",
  "desc": "Dismiss All",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>snh",
  "display": "<Space>snh",
  "label": "Noice History",
  "desc": "Noice History",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>snl",
  "display": "<Space>snl",
  "label": "Noice Last Message",
  "desc": "Noice Last Message",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>snt",
  "display": "<Space>snt",
  "label": "Noice Picker (Telescope/FzfLua)",
  "desc": "Noice Picker (Telescope/FzfLua)",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sp",
  "display": "<Space>sp",
  "label": "Search for Plugin Spec",
  "desc": "Search for Plugin Spec",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sq",
  "display": "<Space>sq",
  "label": "Quickfix List",
  "desc": "Quickfix List",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sr",
  "display": "<Space>sr",
  "label": "Search and Replace",
  "desc": "Search and Replace",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "v:<Space>sr",
  "display": "<Space>sr",
  "label": "Search and Replace",
  "desc": "Search and Replace",
  "mode": "v",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "x:<Space>sr",
  "display": "<Space>sr",
  "label": "Search and Replace",
  "desc": "Search and Replace",
  "mode": "x",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sR",
  "display": "<Space>sR",
  "label": "Resume",
  "desc": "Resume",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>st",
  "display": "<Space>st",
  "label": "Todo",
  "desc": "Todo",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sT",
  "display": "<Space>sT",
  "label": "Todo/Fix/Fixme",
  "desc": "Todo/Fix/Fixme",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>su",
  "display": "<Space>su",
  "label": "Undotree",
  "desc": "Undotree",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sw",
  "display": "<Space>sw",
  "label": "Visual selection or word (Root Dir)",
  "desc": "Visual selection or word (Root Dir)",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "v:<Space>sw",
  "display": "<Space>sw",
  "label": "Visual selection or word (Root Dir)",
  "desc": "Visual selection or word (Root Dir)",
  "mode": "v",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "x:<Space>sw",
  "display": "<Space>sw",
  "label": "Visual selection or word (Root Dir)",
  "desc": "Visual selection or word (Root Dir)",
  "mode": "x",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>sW",
  "display": "<Space>sW",
  "label": "Visual selection or word (cwd)",
  "desc": "Visual selection or word (cwd)",
  "mode": "n",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "v:<Space>sW",
  "display": "<Space>sW",
  "label": "Visual selection or word (cwd)",
  "desc": "Visual selection or word (cwd)",
  "mode": "v",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "x:<Space>sW",
  "display": "<Space>sW",
  "label": "Visual selection or word (cwd)",
  "desc": "Visual selection or word (cwd)",
  "mode": "x",
  "group": "search",
  "groupLabel": "搜索替换",
  "level": 7,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ua",
  "display": "<Space>ua",
  "label": "Toggle Animations",
  "desc": "Toggle Animations",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uA",
  "display": "<Space>uA",
  "label": "Toggle Tabline",
  "desc": "Toggle Tabline",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ub",
  "display": "<Space>ub",
  "label": "Toggle Dark Background",
  "desc": "Toggle Dark Background",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uc",
  "display": "<Space>uc",
  "label": "Toggle Conceal Level",
  "desc": "Toggle Conceal Level",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uC",
  "display": "<Space>uC",
  "label": "Colorschemes",
  "desc": "Colorschemes",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ud",
  "display": "<Space>ud",
  "label": "Toggle Diagnostics",
  "desc": "Toggle Diagnostics",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uD",
  "display": "<Space>uD",
  "label": "Toggle Dimming",
  "desc": "Toggle Dimming",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uf",
  "display": "<Space>uf",
  "label": "Toggle Auto Format (Global)",
  "desc": "Toggle Auto Format (Global)",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uF",
  "display": "<Space>uF",
  "label": "Toggle Auto Format (Buffer)",
  "desc": "Toggle Auto Format (Buffer)",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ug",
  "display": "<Space>ug",
  "label": "Toggle Indent Guides",
  "desc": "Toggle Indent Guides",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uh",
  "display": "<Space>uh",
  "label": "Toggle Inlay Hints",
  "desc": "Toggle Inlay Hints",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ui",
  "display": "<Space>ui",
  "label": "Inspect Pos",
  "desc": "Inspect Pos",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uI",
  "display": "<Space>uI",
  "label": "Inspect Tree",
  "desc": "Inspect Tree",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ul",
  "display": "<Space>ul",
  "label": "Toggle Line Numbers",
  "desc": "Toggle Line Numbers",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uL",
  "display": "<Space>uL",
  "label": "Toggle Relative Number",
  "desc": "Toggle Relative Number",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>un",
  "display": "<Space>un",
  "label": "Dismiss All Notifications",
  "desc": "Dismiss All Notifications",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>up",
  "display": "<Space>up",
  "label": "Toggle Mini Pairs",
  "desc": "Toggle Mini Pairs",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>ur",
  "display": "<Space>ur",
  "label": "Redraw / Clear hlsearch / Diff Update",
  "desc": "Redraw / Clear hlsearch / Diff Update",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>us",
  "display": "<Space>us",
  "label": "Toggle Spelling",
  "desc": "Toggle Spelling",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uS",
  "display": "<Space>uS",
  "label": "Toggle Smooth Scroll",
  "desc": "Toggle Smooth Scroll",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uT",
  "display": "<Space>uT",
  "label": "Toggle Treesitter Highlight",
  "desc": "Toggle Treesitter Highlight",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uw",
  "display": "<Space>uw",
  "label": "Toggle Wrap",
  "desc": "Toggle Wrap",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uz",
  "display": "<Space>uz",
  "label": "Toggle Zen Mode",
  "desc": "Toggle Zen Mode",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>uZ",
  "display": "<Space>uZ",
  "label": "Toggle Zoom Mode",
  "desc": "Toggle Zoom Mode",
  "mode": "n",
  "group": "ui",
  "groupLabel": "界面",
  "level": 8,
  "status": "mapped"
 },
 {
  "id": "n:<Space>-",
  "display": "<Space>-",
  "label": "Split Window Below",
  "desc": "Split Window Below",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>,",
  "display": "<Space>,",
  "label": "Buffers",
  "desc": "Buffers",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>:",
  "display": "<Space>:",
  "label": "Command History",
  "desc": "Command History",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>?",
  "display": "<Space>?",
  "label": "Buffer Keymaps (which-key)",
  "desc": "Buffer Keymaps (which-key)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>.",
  "display": "<Space>.",
  "label": "Toggle Scratch Buffer",
  "desc": "Toggle Scratch Buffer",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>/",
  "display": "<Space>/",
  "label": "Grep (Root Dir)",
  "desc": "Grep (Root Dir)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>`",
  "display": "<Space>`",
  "label": "Switch to Other Buffer",
  "desc": "Switch to Other Buffer",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space><Tab>[",
  "display": "<Space><Tab>[",
  "label": "Previous Tab",
  "desc": "Previous Tab",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space><Tab>]",
  "display": "<Space><Tab>]",
  "label": "Next Tab",
  "desc": "Next Tab",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space><Tab><Tab>",
  "display": "<Space><Tab><Tab>",
  "label": "New Tab",
  "desc": "New Tab",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space><Tab>d",
  "display": "<Space><Tab>d",
  "label": "Close Tab",
  "desc": "Close Tab",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space><Tab>f",
  "display": "<Space><Tab>f",
  "label": "First Tab",
  "desc": "First Tab",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space><Tab>l",
  "display": "<Space><Tab>l",
  "label": "Last Tab",
  "desc": "Last Tab",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space><Tab>o",
  "display": "<Space><Tab>o",
  "label": "Close Other Tabs",
  "desc": "Close Other Tabs",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>|",
  "display": "<Space>|",
  "label": "Split Window Right",
  "desc": "Split Window Right",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>dph",
  "display": "<Space>dph",
  "label": "Toggle Profiler Highlights",
  "desc": "Toggle Profiler Highlights",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>dpp",
  "display": "<Space>dpp",
  "label": "Toggle Profiler",
  "desc": "Toggle Profiler",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>dps",
  "display": "<Space>dps",
  "label": "Profiler Scratch Buffer",
  "desc": "Profiler Scratch Buffer",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>e",
  "display": "<Space>e",
  "label": "Explorer Snacks (root dir)",
  "desc": "Explorer Snacks (root dir)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>E",
  "display": "<Space>E",
  "label": "Explorer Snacks (cwd)",
  "desc": "Explorer Snacks (cwd)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>K",
  "display": "<Space>K",
  "label": "Keywordprg",
  "desc": "Keywordprg",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>l",
  "display": "<Space>l",
  "label": "Lazy",
  "desc": "Lazy",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>L",
  "display": "<Space>L",
  "label": "LazyVim Changelog",
  "desc": "LazyVim Changelog",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>n",
  "display": "<Space>n",
  "label": "Notification History",
  "desc": "Notification History",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>S",
  "display": "<Space>S",
  "label": "Select Scratch Buffer",
  "desc": "Select Scratch Buffer",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>xl",
  "display": "<Space>xl",
  "label": "Location List",
  "desc": "Location List",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>xL",
  "display": "<Space>xL",
  "label": "Location List (Trouble)",
  "desc": "Location List (Trouble)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>xq",
  "display": "<Space>xq",
  "label": "Quickfix List",
  "desc": "Quickfix List",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>xQ",
  "display": "<Space>xQ",
  "label": "Quickfix List (Trouble)",
  "desc": "Quickfix List (Trouble)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>xt",
  "display": "<Space>xt",
  "label": "Todo (Trouble)",
  "desc": "Todo (Trouble)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>xT",
  "display": "<Space>xT",
  "label": "Todo/Fix/Fixme (Trouble)",
  "desc": "Todo/Fix/Fixme (Trouble)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>xx",
  "display": "<Space>xx",
  "label": "Diagnostics (Trouble)",
  "desc": "Diagnostics (Trouble)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 },
 {
  "id": "n:<Space>xX",
  "display": "<Space>xX",
  "label": "Buffer Diagnostics (Trouble)",
  "desc": "Buffer Diagnostics (Trouble)",
  "mode": "n",
  "group": "leader-other",
  "groupLabel": "其他 leader 键",
  "level": 10,
  "status": "mapped"
 }
];
